name: ci

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
    - "**.c"
    - "**.cpp"
    - "**.h"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        comp: [{cc: gcc-14, cxx: g++-14}, {cc: clang-18, cxx: clang++-18}]
        sdl: [true, false]

    env:
      CC: ${{ matrix.comp.cc }}
      CXX: ${{ matrix.comp.cxx }}

    steps:
    - uses: actions/checkout@v5

    - name: Install SDL2
      if: matrix.sdl == true
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev

    - uses: ./.github/workflows/composite-unix


